Fix `test-distributed-charms` CI workflow (#134)
* fic test against CI worklflow

* fix unit and static runs

* Pin Jammy

Signed-off-by: Michael Dmitry <33381599+michaeldmitry@users.noreply.github.com>

---------

Signed-off-by: Michael Dmitry <33381599+michaeldmitry@users.noreply.github.com>

diff --git a/.github/workflows/distributed-solutions-tests.yaml b/.github/workflows/distributed-solutions-tests.yaml
--- a/.github/workflows/distributed-solutions-tests.yaml
+++ b/.github/workflows/distributed-solutions-tests.yaml
@@ -9,7 +9,8 @@ on:
 
 jobs:
   test-distributed-charms:
-    runs-on: ubuntu-latest
+    # Pin due to itests failing on 24.04
+    runs-on: ubuntu-22.04
     continue-on-error: true
 
     strategy:
@@ -26,25 +27,47 @@ jobs:
           fetch-depth: 1
           repository: ${{ matrix.repo }}
           ref: main
+      - name: Install dependencies
+        run: |
+          sudo snap install astral-uv --classic
+          sudo snap install yq
+          pip install tox~=4.2
 
       - name: Update 'cosl' dependency in test charm to this branch
         run: |
+          if [ ! -f requirements.txt ]; then
+            	uv pip compile -q --no-cache pyproject.toml -o requirements.txt
+              uv pip compile -q --no-cache --all-extras pyproject.toml -o requirements-dev.txt
+          fi
           sed -i -e "/^cosl[ ><=]/d" -e "/canonical\/cos-lib/d" -e "/#egg=cosl/d" requirements.txt
           echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@${{ github.head_ref || github.ref_name }}#egg=cosl" >> requirements.txt
-
-      - name: Install dependencies (tox & yq)
-        run: pip install tox~=4.2 && sudo snap install yq
 
       - name: Add charmcraft build dependencies (git)
         run: yq e '.parts.charm.build-packages += ["git"]' -i charmcraft.yaml
 
-      - name: Run the charm's unit & scenario tests
+      - name: Run the charm's unit tests
         id: unit
-        run: tox -e unit,scenario
+        run: |
+          if [ -f tox.ini ]; then  # Run Tox
+            tox -e unit,scenario
+          elif [ -f Makefile ]; then # Run Make
+            make unit
+          else
+            echo "Error: Taskrunner file not found."
+            exit 1
+          fi
 
       - name: Run the charm's static analysis checks
         id: static
-        run: tox -e static-charm,static-lib
+        run: |
+          if [ -f tox.ini ]; then  # Run Tox
+            tox -e static-charm,static-lib
+          elif [ -f Makefile ]; then # Run Make
+            make static
+          else
+            echo "Error: Taskrunner file not found."
+            exit 1
+          fi
 
       - name: Setup Charmcraft's pip cache
         uses: actions/cache@v4
@@ -66,8 +89,16 @@ jobs:
           channel: 1.26-strict/stable
           microk8s-group: snap_microk8s
           microk8s-addons: "hostpath-storage dns metallb:${{ steps.ip_range.outputs.ip_range }}"
-          charmcraft-channel: "2.x/stable"
+          charmcraft-channel: "3.x/candidate"
 
       - name: Run the charm's integration tests
-        run: tox -vve integration
+        run: |
+          if [ -f tox.ini ]; then  # Run Tox
+            tox -vve integration
+          elif [ -f Makefile ]; then # Run Make
+            make integration
+          else
+            echo "Error: Taskrunner file not found."
+            exit 1
+          fi
         if: steps.unit.outcome == 'success' && steps.static.outcome == 'success'
